ls:
  src:
    .dir: kebab-case
    .scss: kebab-case
    .js: kebab-case
    .json: kebab-case
    .png: snake_case
    .jpg: snake_case
    .gif: snake_case
    .webp: snake_case

  src/**/views:
    .vue: kebab-case

  src/**/components:
    .vue: PascalCase

# 一些需要忽略检查的文件
ignore:
  - .git
  - .vscode
  - dist
  - node_modules
